#ifndef BLECONFIG_H
#define BLECONFIG_H

#define APP_COMPANY_IDENTIFIER			0x11BB
#define MANUFACTURER_NAME 				"Lab11UMich"
#define MODEL_NUMBER 					DEVICE_NAME
#define HARDWARE_REVISION 				"A"
#define FIRMWARE_REVISION 				"0.1"

#endif
